#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
function load(file) {
    const context = vm.createContext({});
    const target = path.join(__dirname, '..', file);
    if (fs.existsSync(target)) vm.runInContext(fs.readFileSync(target, 'utf8').replace(/^\.pragma library\s*/, ''), context);
    return context;
}
const rules = load('Titonium/Services/Center/CompactActivityRules.js');
assert.equal(typeof rules.reconcile, 'function', 'Compact needs a tested activity assignment reducer');
const activity = (id, source, extra = {}) => ({ id, source, kind: source, occurredAt: 1, ...extra });
const music = activity('media:current', 'media');
const job = activity('job:build', 'job');
const focus = activity('focus:session', 'focus');
const privacy = activity('capture:recording', 'capture');
let state = rules.reconcile(null, [privacy, focus, music, job]);
assert.equal(state.primaryId, focus.id);
assert.equal(state.secondaryId, privacy.id);
assert.equal(rules.reconcile(null, [job, activity('agent:a', 'agent')]).idle, true);
state = rules.reconcile({...state, manual:true, primaryId:music.id}, [privacy, focus, music]);
assert.equal(state.primaryId, focus.id, 'stale manual selection cannot override priority');
state = rules.reconcile(state, [{...privacy, occurredAt:2}, focus, music]);
assert.equal(state.primaryId, focus.id, 'new privacy does not permanently displace Focus');
state = rules.reconcile(state, [privacy, music]);
assert.equal(state.primaryId, privacy.id);
assert.equal(state.secondaryId, music.id);
state = rules.reconcile(state, [music]);
assert.equal(state.primaryId, music.id);
assert.equal(state.secondaryId, '');
const mic = activity('capture:mic', 'capture');
state = rules.reconcile(null, [privacy, mic]);
const first = state.primaryId;
assert.equal(rules.reconcile(state, [mic, privacy]).primaryId, first, 'ties remain stable');
assert.equal(rules.reconcile(null, [activity('focus:daily', 'focus', {kind:'daily'})]).idle, true);
assert.equal(rules.reconcile(null, [{...music, details:{playbackState:'stopped'}}]).idle, true);
assert.equal(rules.reconcile(null, [{...music, details:{playbackState:'paused'}}]).idle, false);
assert.equal(rules.reconcile(null, [activity('capture:shot', 'capture', {kind:'screenshot'})]).idle, true);
const geometry = load('Titonium/Bar/center/CompactGeometry.js');
assert.equal(typeof geometry.widthFor, 'function');
assert.ok(geometry.widthFor(1920, 36, 200, true, false) < geometry.widthFor(1920, 36, 450, true, false));
assert.ok(geometry.widthFor(3840, 36, 900, true, false) > geometry.widthFor(1920, 36, 900, true, false));
assert.ok(geometry.widthFor(120, 36, 900, true, false) <= 120);
assert.equal(geometry.widthFor(1920, 36, 0, false, true), geometry.widthFor(1920, 36, 900, true, true));
assert.equal(geometry.duration(71), '01:11');
assert.equal(geometry.duration(70), '01:10');
console.log('PASS Compact assignment, privacy sessions, Focus recall, sizing and time formatting');
