const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('Titonium/Services/Mpris/MprisService.qml','utf8');
const match = source.match(/function adjustVolume\(identity: string, delta: real\): bool \{([\s\S]*?)\n    \}/);
assert.ok(match, 'MPRIS needs a guarded player-scoped volume action');
const player = {volume: .5, volumeSupported: true};
const context = vm.createContext({root: {projection: {identity: 'player:a'}, selectedNativePlayer: () => player}});
vm.runInContext('function adjustVolume(identity, delta) {' + match[1] + '\n}',context);
assert.equal(context.adjustVolume('player:b', .1), false);
assert.equal(player.volume, .5);
assert.equal(context.adjustVolume('player:a', .05), true);
assert.equal(player.volume, .55);
assert.equal(context.adjustVolume('player:a', NaN), false);
context.adjustVolume('player:a', 2); assert.equal(player.volume, 1);
context.adjustVolume('player:a', -2); assert.equal(player.volume, 0);
player.volumeSupported = false;
assert.equal(context.adjustVolume('player:a', .1), false);
console.log('PASS player volume targeting, stale identity, capability and bounds');
