#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
qml_import_root="$(mktemp -d --tmpdir titonium-qml-import.XXXXXX)"
trap 'rm -f -- "$qml_import_root/qs"; rmdir -- "$qml_import_root"' EXIT
ln -s -- "$project_root" "$qml_import_root/qs"

python3 "$project_root/scripts/validate_config.py"
python3 "$project_root/scripts/check_settings_schema.py"
python3 "$project_root/scripts/check_protected_contract.py"
python3 "$project_root/scripts/check_skeleton.py"
python3 "$project_root/scripts/check_services.py"
python3 "$project_root/scripts/check_shared_controls.py"
node "$project_root/scripts/check_interaction_feedback.js"
python3 "$project_root/scripts/check_audio.py"
python3 "$project_root/scripts/check_audio_indicators.py"
python3 "$project_root/scripts/check_bar.py"
node "$project_root/scripts/check_classic_bar.js"
node "$project_root/scripts/check_right_pill_state.js"
node "$project_root/scripts/check_connected_popup_content.js"
node "$project_root/scripts/check_bar_popup_routing.js"
node "$project_root/scripts/check_top_bar_style_lifecycle.js"
node "$project_root/scripts/check_edge_menu_geometry.js"
python3 "$project_root/scripts/check_edge_contour.py"
node "$project_root/scripts/check_right_pill.js"
node "$project_root/scripts/check_bar_layout.js"
node "$project_root/scripts/check_bar_visibility.js"
python3 "$project_root/scripts/check_bar_hover_ui.py"
node "$project_root/scripts/check_center_notch.js"
node "$project_root/scripts/check_audio_rules.js"
node "$project_root/scripts/check_audio_geometry.js"
node "$project_root/scripts/check_dock_rules.js"
node "$project_root/scripts/check_dock_actions.js"
python3 "$project_root/scripts/check_dock_store.py"
node "$project_root/scripts/check_dock_mutations.js"
python3 "$project_root/scripts/check_dock.py"
node "$project_root/scripts/check_dock_layout.js"
node "$project_root/scripts/check_dock_menu_geometry.js"
node "$project_root/scripts/check_windows.js"
node "$project_root/scripts/check_active_window.js"
node "$project_root/scripts/check_ui_polish.js"
python3 "$project_root/scripts/check_polish_ui.py"
node "$project_root/scripts/check_system_tray_rules.js"
python3 "$project_root/scripts/check_system_tray.py"
node "$project_root/scripts/check_center_domain.js"
node "$project_root/scripts/check_center_compact.js"
(cd "$project_root" && node scripts/check_capture_feedback.js)
python3 "$project_root/scripts/check_capture_feedback_service.py"
python3 "$project_root/scripts/check_capture_session.py"
python3 "$project_root/scripts/check_screenshot_preview.py"
(cd "$project_root" && node scripts/check_media_title.js && node scripts/check_center_volume.js && node scripts/check_capture_streams.js && node scripts/check_recorder_sessions.js)
python3 "$project_root/scripts/check_recorder_control.py"
python3 "$project_root/scripts/check_media_spectrum.py"
python3 "$project_root/scripts/check_center_compact_ui.py"
node "$project_root/scripts/check_center_surface_state.js"
node "$project_root/scripts/check_center_preview.js"
python3 "$project_root/scripts/check_expanded_content.py"
python3 "$project_root/scripts/check_wallpapers.py"
python3 "$project_root/scripts/check_center_deadline.py"
python3 "$project_root/scripts/check_center_architecture.py"
node "$project_root/scripts/check_center_attention_rules.js"
node "$project_root/scripts/check_center_activity_rules.js"
python3 "$project_root/scripts/check_center_activity.py"
node "$project_root/scripts/check_center_job_rules.js"
python3 "$project_root/scripts/check_center_job.py"
node "$project_root/scripts/check_center_timer_rules.js"
node "$project_root/scripts/check_timer_notification_lifecycle.js"
python3 "$project_root/scripts/check_center_timer.py"
node "$project_root/scripts/check_music_player.js"
python3 "$project_root/scripts/check_music_morph.py"
python3 "$project_root/scripts/check_mpris_tracklist.py"
node "$project_root/scripts/check_mpris_rules.js"
python3 "$project_root/scripts/check_mpris.py"
node "$project_root/scripts/check_center_focus.js"
python3 "$project_root/scripts/check_center_attention.py"
node "$project_root/scripts/check_notifications_rules.js"
node "$project_root/scripts/check_notification_policy_rules.js"
node "$project_root/scripts/check_notification_coordinator_rules.js"
python3 "$project_root/scripts/check_notification_coordinator.py"
node "$project_root/scripts/check_notification_panel_routing.js"
node "$project_root/scripts/check_notification_panel_lifecycle.js"
node "$project_root/scripts/check_notification_theme_contract.js"
node "$project_root/scripts/check_notification_settings_rules.js"
python3 "$project_root/scripts/check_notification_panel.py"
node "$project_root/scripts/check_system_monitor_rules.js"
python3 "$project_root/scripts/check_system_monitor.py"
node "$project_root/scripts/check_center_presentation_rules.js"
node "$project_root/scripts/check_classic_center_popup_transition.js"
python3 "$project_root/scripts/check_notifications.py"
python3 "$project_root/scripts/check_notification_dispatch.py"
node "$project_root/scripts/check_workspaces.js"
node "$project_root/scripts/check_hyprland_refresh.js"
node "$project_root/scripts/check_workspace_colors.js"
node "$project_root/scripts/check_window_switcher_rules.js"
python3 "$project_root/scripts/check_window_switcher.py"
python3 "$project_root/scripts/check_surface_passthrough.py"
node "$project_root/scripts/check_surface_identity.js"
node "$project_root/scripts/check_focus_ownership.js"
python3 "$project_root/scripts/check_focus_handoff_trace_test.py"
python3 "$project_root/scripts/check_session_lock.py"
node "$project_root/scripts/check_bluetooth_rules.js"
python3 "$project_root/scripts/check_bluetooth.py"
python3 "$project_root/scripts/check_bluetooth_agent.py"
node "$project_root/scripts/check_wifi_rules.js"
python3 "$project_root/scripts/check_wifi.py"
python3 "$project_root/scripts/check_wifi_password.py"
node "$project_root/scripts/check_screen_policy.js"
node "$project_root/scripts/check_preferences.js"
node "$project_root/scripts/check_appearance_rules.js"
node "$project_root/scripts/check_design_styles.js"
node "$project_root/scripts/check_style_rules.js"
node "$project_root/scripts/check_style_layout_contract.js"
python3 "$project_root/scripts/check_style_controls.py"
python3 "$project_root/scripts/check_style_layout_ui.py"
python3 "$project_root/scripts/check_style_consumers.py"
python3 "$project_root/scripts/check_style_integration.py"
node "$project_root/scripts/check_appearance_transaction.js"
python3 "$project_root/scripts/check_appearance_coordinator.py"
python3 "$project_root/scripts/check_appearance_ui.py"
python3 "$project_root/scripts/check_appearance_material.py"
python3 "$project_root/scripts/check_wallpaper_transaction.py"
python3 "$project_root/scripts/check_wallpaper_recovery.py"
python3 "$project_root/scripts/check_preferences_store.py"
python3 "$project_root/scripts/check_preferences_runtime.py"
node "$project_root/scripts/check_settings_catalog.js"
python3 "$project_root/scripts/check_settings.py"
python3 "$project_root/scripts/check_settings_pages.py"
python3 "$project_root/scripts/check_settings_ui.py"
node "$project_root/scripts/check_typography.js"
node "$project_root/scripts/check_icon_rules.js"
node "$project_root/scripts/check_application_launch.js"
node "$project_root/scripts/check_application_visibility.js"
node "$project_root/scripts/check_spotlight.js"
node "$project_root/scripts/check_spotlight_selection.js"
node "$project_root/scripts/check_spotlight_wheel.js"
node "$project_root/scripts/check_clipboard_history.js"
node "$project_root/scripts/check_clipboard_regressions.js"
python3 "$project_root/scripts/check_clipboard_io.py"
node "$project_root/scripts/check_clipboard_access.js"
node "$project_root/scripts/check_clipboard_center_rules.js"
node "$project_root/scripts/check_clipboard_format.js"
node "$project_root/scripts/check_agent_approval.js"
python3 "$project_root/scripts/check_agent_approval_bridge.py"
python3 "$project_root/scripts/check_approval_proxy.py"
python3 "$project_root/scripts/check_approval_bridge_logging.py"
node "$project_root/scripts/check_agent_approval_security.js"
bash -n "$project_root/scripts/center_notch_acceptance.sh"
bash -n "$project_root/scripts/center_attention_acceptance.sh"
bash -n "$project_root/scripts/center_activity_acceptance.sh"
bash -n "$project_root/scripts/center_job_acceptance.sh"
bash -n "$project_root/scripts/center_timer_acceptance.sh"
bash -n "$project_root/scripts/mpris_acceptance.sh"
bash -n "$project_root/scripts/audio_acceptance.sh"
bash -n "$project_root/scripts/dock_acceptance.sh"
bash -n "$project_root/scripts/bluetooth_acceptance.sh"
bash -n "$project_root/scripts/wifi_acceptance.sh"
bash -n "$project_root/scripts/window_switcher_acceptance.sh"
bash -n "$project_root/scripts/workspace_interactions_acceptance.sh"
bash -n "$project_root/scripts/notifications_acceptance.sh"
bash -n "$project_root/scripts/system_monitor_acceptance.sh"
bash -n "$project_root/scripts/settings_acceptance.sh"
bash -n "$project_root/scripts/protected_acceptance.sh"

mapfile -d '' qml_files < <(find "$project_root" -type f -name '*.qml' -print0 | sort -z)
qml_output="$(/usr/lib/qt6/bin/qmllint -I "$qml_import_root" "${qml_files[@]}" 2>&1)"
printf '%s\n' "$qml_output"

unexpected_warnings="$(printf '%s\n' "$qml_output" \
    | rg '^Warning:' \
    | rg -v -f "$project_root/scripts/qmllint_allowlist.txt" || true)"
if [[ -n "$unexpected_warnings" ]]; then
    printf 'FAIL unexpected qmllint warnings:\n%s\n' "$unexpected_warnings" >&2
    exit 1
fi

echo "PASS qmllint"
