#!/usr/bin/env node
// Catches lost unrelated drafts, cross-mode custom edits and stale trial rollback.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const file = path.join(__dirname, '../Titonium/Settings/AppearanceTransaction.js');
const t = vm.createContext({});
if (fs.existsSync(file)) vm.runInContext(fs.readFileSync(file,'utf8'),t);
assert.equal(typeof t.mergeCandidate, 'function', 'Appearance transaction merge exists');
const plain=x=>JSON.parse(JSON.stringify(x));
const settings={appearance:{mode:'dark',themeId:'neutral',themeOverrides:{},wallpaper:{policy:'keep',customPath:''}},accessibility:{reducedMotion:false},locale:'vi',modules:{bar:{style:'connected'},audio:{allowAmplification:false}}};
const base=t.pick(settings), candidate=plain(base);
candidate.appearance.themeId='glass';
const other=plain(settings); other.locale='en';other.modules.audio.allowAmplification=true;other.accessibility.reducedMotion=true;
const merged=plain(t.mergeCandidate(other,base,candidate));
assert.equal(merged.locale,'en');assert.equal(merged.modules.audio.allowAmplification,true);
assert.equal(merged.accessibility.reducedMotion,true,'untouched appearance Reduced Motion must not overwrite General draft');
assert.equal(merged.appearance.themeId,'glass');assert.equal(merged.modules.bar.style,'connected');
assert.equal(settings.appearance.themeId,'neutral','merge must not mutate source');
let changed=t.override(candidate,'dark','accent','#aa22ff');
assert.equal(changed.appearance.themeOverrides.glass.dark.accent,'#aa22ff');
changed=t.override(changed,'light','accent','#003388');
assert.equal(changed.appearance.themeOverrides.glass.dark.accent,'#aa22ff');
assert.equal(changed.appearance.themeOverrides.glass.light.accent,'#003388');
changed=t.override(changed,'dark','accent',null);
assert.equal(changed.appearance.themeOverrides.glass.dark.accent,undefined);
assert.equal(changed.appearance.themeOverrides.glass.light.accent,'#003388');
assert.deepEqual(plain(t.override(changed,'dark','__proto__',{polluted:true})),plain(changed));
assert.deepEqual(plain(t.override(changed,'system','accent','#ffffff')),plain(changed));
const trial=t.trial(4,1000,candidate);
assert.equal(t.expired(trial,15999,4),false);assert.equal(t.expired(trial,16000,4),true);
assert.equal(t.expired(trial,17000,3),false,'stale timer cannot close current trial');
assert.equal(trial.candidate.appearance.themeId,'glass');candidate.appearance.themeId='soft';
assert.equal(trial.candidate.appearance.themeId,'glass','trial snapshot immutable from edits');
const after=plain(merged);after.locale='vi';after.modules.bar.height=64;
const undo=t.restoreAppearance(after,settings,merged);
assert.equal(undo.appearance.themeId,'neutral');assert.equal(undo.locale,'vi');assert.equal(undo.modules.bar.height,64);
assert.equal(undo.accessibility.reducedMotion,true,'undo must not revert Reduced Motion changed independently');
const moduleSettings={appearance:{themeId:'neutral'},modules:{bar:{style:'connected',height:44},dock:{style:'follow-topbar'}},accessibility:{reducedMotion:false}};
const moduleBase=t.pick(moduleSettings);
const moduleNext=t.mergeCandidate(moduleSettings,moduleBase,{appearance:{themeId:'material',mode:'dark'},reducedMotion:false});
assert.deepEqual(plain(moduleNext.modules),moduleSettings.modules,'Appearance merge preserves every module');
assert.equal(t.override({appearance:{themeId:'neumorphism'}},'dark','shadowStrength',.8).appearance.themeOverrides.neumorphism.dark.shadowStrength,.8);
console.log('PASS appearance draft merging, override isolation, immutable trial deadlines and scoped undo');
