const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const r=vm.createContext({});
const file='Titonium/Services/Capture/CaptureFeedbackRules.js';
if(fs.existsSync(file))vm.runInContext(fs.readFileSync(file,'utf8').replace(/^\.pragma library\s*/,''),r);
assert.equal(typeof r.screenshot,'function','capture feedback needs exact screenshot routing');
const shot={key:'n:1',summary:'Screenshot saved',body:'/home/test/Pictures/Screenshots/Shot #1.png'};
const event=r.screenshot(shot,1000,'/home/test/Pictures/Screenshots');
assert.equal(event.context.details.imageUrl,'file:///home/test/Pictures/Screenshots/Shot%20%231.png');
assert.equal(event.expiresAt,7000);
assert.equal(r.screenshot({...shot,body:'https://example.com/a.png'},1000,'/home/test/Pictures/Screenshots'),null);
assert.equal(r.screenshot({...shot,summary:'Other notification'},1000,'/home/test/Pictures/Screenshots'),null);
assert.equal(r.screenshot({...shot,body:'/home/test/Pictures/Screenshots/../secret.png'},1000,'/home/test/Pictures/Screenshots'),null);
let state=r.publish(r.initialState(),event);
state=r.select(state,event.context.id);
const newer=r.screenshot({...shot,key:'n:2',body:'/home/test/Pictures/Screenshots/Shot2.png'},2000,'/home/test/Pictures/Screenshots');
state=r.publish(state,newer);
assert.equal(state.selected.details.imageUrl,event.context.details.imageUrl,'new event cannot replace opened screenshot');
assert.equal(r.expire(state,event.id,7000),state,'old timer cannot expire a newer event');
assert.equal(r.expire(state,newer.id,7999),state);
state=r.expire(state,newer.id,8000);
assert.equal(state.feedback,null);
assert.equal(r.contexts(state).length,1,'opened preview survives expiry');
state=r.select(state,'');
assert.equal(r.contexts(state).length,0,'closing releases expired screenshot');
const focus={id:'focus:session',source:'focus'},rec={id:'capture:recording:100',source:'capture',kind:'screen-recording'},music={id:'media:current',source:'media'};
const selection={primaryId:focus.id,secondaryId:rec.id};
let compact=r.project(selection,[focus,rec,music],event);
assert.equal(compact.primary.id,event.context.id);
assert.equal(compact.secondary.id,focus.id);
assert.equal(compact.recordingIndicator.id,rec.id);
compact=r.project(selection,[focus,rec,music],null);
assert.equal(compact.primary.id,focus.id);
assert.equal(compact.secondary.id,rec.id);
const started=r.recording(100,1000);
compact=r.project({primaryId:rec.id,secondaryId:music.id},[rec,music],started);
assert.equal(compact.primary.id,rec.id);
assert.equal(compact.secondary.id,music.id);
assert.equal(compact.primary.details.feedbackKind,'recording_started');
compact=r.project({primaryId:rec.id,secondaryId:music.id},[rec,music],null);
assert.equal(compact.primary.id,rec.id,'expiry does not restore Music over Recording');
compact=r.project({primaryId:'',secondaryId:''},[],event);
assert.equal(compact.idle,false);
assert.equal(r.project({primaryId:'',secondaryId:''},[],null).idle,true);
assert.equal(started.contextId,'capture:recording:100','feedback opens its exact recording session');
const surface=vm.createContext({});
vm.runInContext(fs.readFileSync('Titonium/Core/Surfaces/Center/CenterSurfaceState.js','utf8').replace(/^\.pragma library\s*/,''),surface);
for (const mode of ['banner','expanded']) {
 const old=surface.stateValue({mode,ownerScreenName:'DP-1',selectedContextId:'capture:recording:100',generation:3});
 const replacement={id:'capture:recording:200'};
 const closed=surface.transition(old,{contexts:[replacement],primary:replacement},{type:'snapshot-changed'},200);
 assert.equal(closed.mode,'compact','retired recording Normal closes instead of retargeting');
 assert.equal(closed.selectedContextId,'','retired recording clears its selected target');
}

console.log('PASS capture feedback expiry, exact preview, session targeting, retention and slot projection');
